

INCLUDE_PATHS = \
		-I$(STAGING_DIR)/usr/include/natalie-dect/ \
		-I$(STAGING_DIR)/usr/include/natalie-dect/Phoenix  \


all:
	$(GCC) $(INCLUDE_PATHS) -o dect-prog boot.c tty.c error.c main.c state.c util.c preloader.c flashloader.c Crc.c app.c buffer.c packet.c





